import { Inter , IBM_Plex_Sans_Arabic  , Gulzar , Red_Hat_Display} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });


const gulzar = Gulzar({
  subsets:['arabic'],
  weight : ['400'],
  variable : '--font-Gulzar'
})


const Red = Red_Hat_Display({
  subsets:['latin'],
  weight: '400',
  variable : '--font-Red_Hat_Display'
})


const IBM = IBM_Plex_Sans_Arabic({
  subsets : ['arabic'],
  weight : [ '100' , '200' , '300' , '400' , '500' , '600' , '700'],
 variable : '--font-IBM_Plex_Sans_Arabic'
})




export const metadata = {
  title: "astery-marketing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${IBM.variable} ${gulzar.variable} ${Red.variable}`}>{children}</body>
    </html>
  );
}
