import { Inter , IBM_Plex_Sans  ,   Red_Hat_Display , Sevillana , Bruno_Ace_SC } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });


const sevillana = Sevillana({
  subsets:['latin'],
  weight : ['400'],
  variable : '--font-Sevillana'
})


const Red = Red_Hat_Display({
  subsets:['latin'],
  weight: '400',
  variable : '--font-Red_Hat_Display'
})


const Bur = Bruno_Ace_SC({
  subsets : ['latin'],
weight : ['400'],
 variable : '--font-Bruno_Ace_SC'
})




export const metadata = {
  title: "astery-marketing",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Bur.variable} ${sevillana.variable} ${Red.variable}`}>{children}</body>
    </html>
  );
}
